### ISSUE TITLE
The binary is broken

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#103]
When you deleted the binary/linux/lib/library directory it broke the linux binary, please revert this commit

**Comment by glaukiol1** [comment]
And also, please dont change licenses of the source code in the binaries, you cant do that

**Comment by CertifiedRice** [comment]
oh shoot 
sorry

**Comment by glaukiol1** [comment]
Dont worry about it, i was just saying it because u didnt seem aware of it, thanks for responding!
