### ISSUE TITLE
Compiling to web code.

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#106]
There needs to be a way to compile Rusted Script code into JavaScript code so that the web browser can read it.
There will be a way for the user to add a directory for where the HTML file with a script tag should be placed. 
For example: 
```JSON
{
   "html-source": "c:user/idk/desktop/project/src",
   "javascript-source": "c:user/idk/desktop/project/src/scripts",
   "script-name": "test"
}
```

```html
<html>
<body>
     <script src"script/test,js"></script>
</body>
</html>
```

the JSON file has the info on where to make the source files and what to name the files.  
This will be useful for making websites.

**Comment by glaukiol1** [comment]
then you would need to make a compiler, which is basically rebuilding the whole language
