### ISSUE TITLE
binary for linux and mac 

### ISSUE THREAD

**Issue by ChristanNevanaSansdoria** [Rusted-Script/Rusted-Script#107]
There needs to be binaries for linux and mac, although most serves run on linux, people still need to be able to run Rusted Script with the binary, so making one for Mac and Windows might be a good idea. And some servers still use Mac and Windows.

**Comment by glaukiol1** [comment]
Well we already have binaries for linux, and we are working on getting them for windows and Mac OS X. Thanks!
