### ISSUE TITLE
Working with Data and Back-end

### ISSUE THREAD

**Issue by ChristanNevanaSansdoria** [Rusted-Script/Rusted-Script#111]
There needs to be a way to interact with data(sql) and back-end. 
For data, there could be functions where it creates, deletes, inject, and read tables in SQL. Back-end features will create a web(http) server where it can do things. This will become useful when making server side applications.

**Comment by CertifiedRice** [comment]
sorry, but no. Rusted Script is not going to be based around Data. But you can create a framework for working with Data for Rusted Script if you want to.
