### ISSUE TITLE
lol?

### ISSUE THREAD

**Issue by sufficients** [Rusted-Script/Rusted-Script#113]
why is this so blatantly ran by someone under the age of 13?
you are literally talking to yourself by making alt accounts and making issues on them.
for example:
 - @issacehogan (**REAL DISCORD SOFTWARE ENGINEER BTW**) joined 15 days ago, doesn’t have any contributes to any of discord’s repositories and is just a blatantly fake alt.
 - @calvin-smith1 (**posing to be a google software engineer**) joined 16 days ago, again; 
doesn’t have any contributes to any of google’s repositories, 
and literally has contributed to no repositories but “rusted-script” (the language that can’t even compile btw) just like the other fake account

couldn’t have you just tried a little harder?
cmon bro, you could have just atleast waited a month to get the “Joined {insert days ago} days ago” off the accounts so they could look a little more convincing.

**Comment by sufficients** [comment]
you’ll probably just close this, but i don’t really care

**Comment by CertifiedRice** [comment]
wtf 

idk, but they stopped
