### ISSUE TITLE
Web development support 

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#16]
When I started to work on the programming language, I had an idea of adding Game/Web/Mobile development support to the programming language. Where you can make stunning websites, action packed games and cool mobile apps while using only 1 programming language. So I think the easiest start to this is starting with web development.

**Comment by glaukiol1** [comment]
I would love to make a Web Dev package to this langauge, like ExpressJS for javascript, but I think you should first finish the main programming langauage, such as functions etc.. My suggestion is that in the future you can also add imports, the equivalent of `from package-name import *` in python. Good luck! I will keep contributing

**Comment by CertifiedRice** [comment]
hmm ok ok
