### ISSUE TITLE
Add Support For Code Blocks

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#17]
# Add Support For Code Blocks

Code Blocks for if statements & more, for example
```js
if 1 == 1 then {
// Code block
}
```
Currently, if we run this, we will get a `Illegal Character: '"'` Error.

**Comment by CertifiedRice** [comment]
hmmmm
Good idea

**Comment by CertifiedRice** [comment]
I might only do it for Functions and While Loops

**Comment by glaukiol1** [comment]
Of course, but what if you are trying to run multiple lines of code in a if statement? Its very common for that to happen, this would be an example, in python
```py
price = 20
customers = 0
income = 0
# lets imagine we have a Customer class
first_customer = Customer("Bob")
if (first_customer.hasPayed()):
    income += price
    customers += 1
```
In this case, we are running two lines, but i have made Web Apps using ExpressJS that have 100s of lines of code in a if statement, so you can decide.

**Comment by CertifiedRice** [comment]
hmmm, no code blocks for if statements. But add code blocks for Functions and While Loops

**Comment by glaukiol1** [comment]
Then how would you run a multi-line if statement?
Just wondering

**Comment by CertifiedRice** [comment]
idk
depends 
`if first_customer = hasPayed then income += price then customers += 1`

**Comment by glaukiol1** [comment]
Yes, that could work, but what if there were 50 lines you need to write? Plus in this way it would be almost impossible to read the code, because it would look some thing like this;
```
if first_customer == hasPayed then income += price then # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #   # statement #  else # statement #
```
I understand what you mean, but in that way it will be impossible to debug/read the code.

**Comment by CertifiedRice** [comment]
we can make the user able to define a statement in another line so 
```
if blah_blah == true then statement.new("bruhNoU")
BruhNoU = {
      print("no why?")
}
```
and then the user can call the same statement in other if statements and such
so 
```
if x == 4 then BruhNoU()
```

**Comment by glaukiol1** [comment]
Oh thats amazing! It will work, thanks! Im closing this now.
