### ISSUE TITLE
Functions and Printing 

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#19]
All programming languages need functions and printing. 
So they way printing is gonna work is simple. `print("string" + orVariable)`
And functions will be simple
```
function printBruh() {
      print("Bruh)
     }

printBruh()

**Comment by glaukiol1** [comment]
That looks amazing! Just one more suggestion, Rusted Script needs pre-defined functions, what i mean is something like this;
```py
# one pre-defined function in python is;
print()
# You dont need to make a function named print to do that, and there are many more!
```
There are a lot more, especially classes, like `str()` `int()` and many more. I like the way Rusted Script is being developed!

**Comment by CertifiedRice** [comment]
yeah
