### ISSUE TITLE
Comments in Rusted Script

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#20]
# Comments in Rusted Script

I have a simple question, how do we comment in Rusted Script, i want to update some files and the new `src/interpreter.py` that i made today based on it. Thanks!
Common comment types are;
```
//
# 
/*  */
```

**Comment by CertifiedRice** [comment]
//
/* */
and 
#

**Comment by glaukiol1** [comment]
So all of them 😃?

**Comment by CertifiedRice** [comment]
yes lol

**Comment by glaukiol1** [comment]
Ok im going to work on the interpreter tomorrow cause ima sleep rn. Closing this
