### ISSUE TITLE
Functions, Logging, Modules, and Server

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#26]
the last few things we need to add is Functions, Logging, Modules, and Server-Side Stuff 
```
// Functions
function bruh() {
     if x == 1 then console.print("no lol")
}
```

```
// logging
/*
Logging will print stuff in the console, in can print strings, number, value, or any type of data
*/
var x = 1
console.print("1 * 1 = " + x)
```

Modules are just other files. For example the server could do `use(bruh.rusted)` in it will include the contents. So if in `bruh.rusted` there is a variable the user can use that variable in other files as long as they include `use(bruh.rusted)`
```
// modules 
use("Discord.rusted")
var Client = discord.client = new
```

The Server part of Rusted-Script will allow the user to run code, so if they were creating a website they can use Rusted-Script as the back-end. And they can host it locally or put it on a server to run it. 

```
use(Server)

var port = 5000

http("localhost::" + port)

```

**Comment by glaukiol1** [comment]
I am going to work on the interpreter to be able to include .rusted files! It will be finished shortly!

**Comment by CertifiedRice** [comment]
epic
