### ISSUE TITLE
Classes | Functions | Code Blocks

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#29]
The next steps in making *Rusted Script* are making classes, function, and code blocks. When they are done, I will help make the pre-defined classes and functions. Such as `int()` `str()` and many more. I will also develop a module in rusted script for web development, something like django in python or express in javascript. Code Blocks are needed for classes and functions, as they need a lot of lines of code inside them.

**Comment by CertifiedRice** [comment]
ok
