### ISSUE TITLE
printing 

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#30]
Printing will log stuff on the terminal 
```
# Printing in Rusted Script 
console.print("hmm yes yes ")
```

Anything in the string(so for example `"bruh"`) will become a python variable with the string `"bruh"` and then it will print the python variable. 

...There might be a better way on doing this

**Comment by glaukiol1** [comment]
Well make a way to define functions first, and then we can make a directory `src/lang-inculdes`, where all the pre-defined functions and variables will be defined, such as `console` and the function `print` on the console class, so definitely functions and classes have to be finished first in my opinion.

**Comment by CertifiedRice** [comment]
hmmmm
ok
