### ISSUE TITLE
I highly think that the `includes` folder has junk in it, and about these "*Google Interns*"

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#41]
Hello,
I have been contributing to Rusted Script 1 and a half week ago, and the contributions to the `include` folder by these *"Google Inters"*, which i highly think that they are not, and that is a different story, but what is the point of having pre-defined variables named "one" to "zero" and assign them to integers? Also why would we need upper-case booleans? If these "*Google Interns*" can explain this to me that would be nice. There have recently have been a lot of scams on GitHub of people pretending to work at these big companies, and i think these people are one of them, they both joined GitHub yesterday and claim to be "*Google Inters*", with no affinition to Google projects ***at all***. Please @CertifiedRice, be careful and review their pull requests carefully.
Thanks!

**Comment by glaukiol1** [comment]
They are following real Google interns, who **are** in the official Google GitHub, and these people who have joined GitHub yesterday, are saying they working as Google Inters, but really arent even in the Google GitHub!

**Comment by CertifiedRice** [comment]
I was reviewing their pull request last night. The code didn't have any bad stuff in it.
But they were adding useless junk into it

**Comment by CertifiedRice** [comment]
I feel like they are faking their **Google Internship** because they joined yesterday, all they did was code review on a random repository on google GitHub. An average software engineer from a big company that just joined GitHub TODAY. What do they have on their resume? How did they even get a job? 
They are not causing harm to the development of Rusted Script but they are adding the most useless junk.

**Comment by glaukiol1** [comment]
Yes, they use this to get your trust, and later they might put intentional bugs and or viruses.

**Comment by glaukiol1** [comment]
> I feel like they are faking their **Google Internship** because they joined yesterday, all they did was code review on a random repository on google GitHub. An average software engineer from a big company that just joined GitHub TODAY. What do they have on their resume? How did they even get a job?
> They are not causing harm to the development of Rusted Script but they are adding the most useless junk.

Yes, I have friend who got a job at Microsoft, and they checked his GitHub profile before anything!

**Comment by glaukiol1** [comment]
Im closing this, just be careful in the future
