### ISSUE TITLE
Website improvement ideas

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#46]
Hello. I made the Rusted Script website. It is very basic. 
If you have any improvement ideas you can comment on this issue or create a pull request [here](https://github.com/Rusted-Script/rusted-script.github.io)

**Comment by glaukiol1** [comment]
Is the website on GitHub, if so can you send me a link, after all what I do is web development, ill contribute to it!

**Comment by CertifiedRice** [comment]
https://github.com/Rusted-Script/rusted-script.github.io

**Comment by glaukiol1** [comment]
Thanks!

**Comment by CertifiedRice** [comment]
you're welcome 😄

**Comment by glaukiol1** [comment]
I made a small pull request there
