### ISSUE TITLE
Making a `build.py` file in the `src` folder

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#49]
# Making a `build.py` in the `src` folder
We can make a build.py in the main folder, it will compile all of the rusted script source code into one `rusted.exe` file, and here is the rusted script CLI, where you can run commands like `rusted run ./main.rusted` or `rusted install https://github.com/blablalba`.

**Comment by glaukiol1** [comment]
What do you think?

**Comment by CertifiedRice** [comment]
yes good
yes yes yes yes yes yes 
good
very nice
pogs

**Comment by CertifiedRice** [comment]
we will also need a version for Linux 
mac users will just use the source code lol

**Comment by glaukiol1** [comment]
lol mac os is a unix based system, so most stuff on linux also works on mac, and i have dual boot (Windows 10 & Kali Linux Debian 8) so i can test both operating systems.

**Comment by glaukiol1** [comment]
I will work on this later
