### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#5]
# Questions About Rusted Script

1. How can you print to the terminal? (console.log() in js or print() in py)
2. How can you write a function? A code example please.
3. How to run a *.rusted* file?
4. What is the use of Rusted Script? What can it be used for?
5. Is it a compiled language? (eg. c++) or a interpreted langauage (eg. py)?
6. Would you like me to contribute to this project? Im looking to contribute in a lot of projects and I like this one. I have extensive knowledge in Python and JavaScript.

**Comment by CertifiedRice** [comment]
Well, I am still working on the programming language. 
I am currently using python to run the code and the terminal to code with the programming language.
.rusted files currently are just for examples(I am working on a way to use it).
No, currently there are no ways to write functions(but I am looking forward on making a way to write functions) 
Yes, I am looking for contributors.
And thank you on fixing the docs, it looks great! 😄

**Comment by glaukiol1** [comment]
Thanks!
