### ISSUE TITLE
Security features 

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#50]
I feel like it would be a good idea to add security features. So it will prompt you to give permission if you're going to access Files, os, memory, storage, HTTP request, or others. This will prevent hijacking via taking code mindlessly from the internet or from some fishy dude you met. So if it is gonna let's say wipe out all of your storage, it will prompt you with a
```
Are you sure you want to access this?
Source:
[
        c:user 
        system32
]

if you are sure please use "allow access files" in your run command 
```
or 
```
Are you sure you want to access the HTTP source of "heroku.com` 
source:
line 123 string "token.env"
```

This is like how Deno or Rust works. 
you can also use the `unsafe` function in your run command and will give permission to everything. 
so `rusted run -unsafe access_hard-drive.rusted` will just give access to everything. Or if you want to give access to something specific for example files, you could do `rusted run -files delete_bruh-txt`

**Comment by issacehogan** [comment]
that seems like a great idea!
