### ISSUE TITLE
Shell Errors Out

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#6]
# Shell.py terminates
shell.py *always* terminates when you put one of the following characters; “ OR ‘
Whenever you put a quote or double quote, there is an error message like the following, and the script terminates.
“illegal_char_error is not defined”

**Comment by CertifiedRice** [comment]
yes ,the shell terminates when you run a script with an Illegal Character. 
I haven't really added support for quote(') or double quote(") 
But I am planning on adding that soon

**Comment by glaukiol1** [comment]
Ok thanks!
