### ISSUE TITLE
Making a global script

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#61]
# Making a global script

My idea is that we make a global script named something like `main.py`, it is the *Rusted Script* CLI file where you can run sub commands such as `run`, that would call the `src/interpreter.py` file, and more, like `install` to install *rusted_modules*. Then we can make a script for Windows & Linux that installs this script to *PATH*, and you can run it simply, like `rusted install test_package` or `rusted run hello.rusted`. What do you think?

**Comment by CertifiedRice** [comment]
looks good!
