### ISSUE TITLE
Making a compiler 

### ISSUE THREAD

**Issue by CertifiedRice** [Rusted-Script/Rusted-Script#7]
Rusted-Script needs a fast compiler that can run **.rusted** files that will compile into rusted script.

**Comment by glaukiol1** [comment]
You mean a interpreter, or a compiler?
A compiler is a piece of code that converts in our case .rusted files to for example .cpp files. A interpreter gets the rusted code and runs it as it is, no need to convert it to another langauge. So which one? Im working on a simple interpreter for rusted script.

**Comment by CertifiedRice** [comment]
Interpreter sounds good 😄

**Comment by glaukiol1** [comment]
Ok!

**Comment by CertifiedRice** [comment]
Ok thank you
