### ISSUE TITLE
What happend with updaters?

### ISSUE THREAD

**Issue by glaukiol1** [Rusted-Script/Rusted-Script#74]
The files `updaters/*` were removed. Where did they go? You also removed the shells/ and installers/ dirs 😢. Good luck!

**Comment by glaukiol1** [comment]
Can you bring back the updaters? I loved them lol

**Comment by CertifiedRice** [comment]
they are still there

**Comment by CertifiedRice** [comment]
I just removed them from the folders 
so it didn't mess the directory up

**Comment by CertifiedRice** [comment]
https://github.com/Rusted-Script/Rusted-Script/blob/master/Linux_Installer.sh
https://github.com/Rusted-Script/Rusted-Script/blob/master/windows_shell.bat
https://github.com/Rusted-Script/Rusted-Script/blob/master/linux_shel.sh
https://github.com/Rusted-Script/Rusted-Script/blob/master/Windows_Installer.bat

**Comment by glaukiol1** [comment]
I mean i dont see `Windows_Updater.bat` and `Linux_Updater.sh`?

**Comment by CertifiedRice** [comment]
oh crap, forgot about them. lemme make them again

**Comment by CertifiedRice** [comment]
https://github.com/Rusted-Script/Rusted-Script/blob/master/Linux_Updater.sh
https://github.com/Rusted-Script/Rusted-Script/blob/master/Windows_Updater.bat

**Comment by glaukiol1** [comment]
Thanks 😀
