### ISSUE TITLE
Hello. I am a Data Scientist at facebook. 

### ISSUE THREAD

**Issue by ChristanNevanaSansdoria** [Rusted-Script/Rusted-Script#85]
I am currently switching to the Software Engineer team at facebook. I am on the Objective-Rusted team. What is Objective-Rusted? Objective-Rusted is a programming language based on Rusted Script and Rust. It is still in it's early stages of development! I want to learn more about Rusted Script.  I will keep contributing to it! I have many features in mind.

**Comment by glaukiol1** [comment]
Oh not another one of these big company inters please we are already done with these fakes

**Comment by CertifiedRice** [comment]
I am pretty sure impersonation is against the GitHub TOS and Community Guidelines 🤔
