### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by ChristanNevanaSansdoria** [Rusted-Script/Rusted-Script#90]
In most programming languages. They have binaries. Those allow you to compile the source code of the programming language with out lets say installing python or .NET core. For example, the Lua Windows 32 binaries are just filled with dll and executables. It might be a good idea to make a binaries for each platform, for example if you were going to make one for IOS you would use Swift or Objective-C, or for Android you would use Java or Kotlin. For Windows, Mac, and Linux it would be lets say, either compiled via the source(python) or could be used with Swift(Mac) Kotlin(Linux) or C(Windows and Linux)

**Comment by CertifiedRice** [comment]
they are now out for linux!
