### ISSUE TITLE
Data Science/Engineer/Analyzing or Machine Learning/AI support  

### ISSUE THREAD

**Issue by ChristanNevanaSansdoria** [Rusted-Script/Rusted-Script#97]
I think it would be a a great idea to add something similar to Jupyter Notebook in Rusted Script!

**Comment by CertifiedRice** [comment]
although that would be a great idea! I don't intend on adding that feature. Rusted Script is not a Data focused programming language. But you can make a package for Data Science/Machine learning if you want to!
